MKSPIFFS_COMPONENT_PATH := $(COMPONENT_PATH)
MKSPIFFS_BUILD_DIR=$(abspath $(MKSPIFFS_COMPONENT_PATH)/mkspiffs)

# Custom recursive make for mkspiffs sub-project
MKSPIFFS_MAKE=+$(MAKE) -C $(MKSPIFFS_COMPONENT_PATH)/src

#Change clean to mkspiffs_clean to avoid name clash with esp-idf clean target
.PHONY: mkspiffs_clean

mkspiffs:
	$(MKSPIFFS_MAKE) all

mkspiffs_clean:
	$(MKSPIFFS_MAKE) clean

